name: Update README with Time Since Birth

on:
  schedule:
    - cron: "0 */2 * * *"  
  workflow_dispatch:        

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  

      - name: Configure Git
        run: |
          git config --global user.email "anupgautam430@gmail.com"
          git config --global user.name "Anup Gautam"

      - name: Install dependencies
        run: |
          npm install

      - name: Run update script
        run: |
          node updateTime.js

      - name: Check for changes in README.md
        id: check_changes
        run: |
          if [[ -z $(git status --porcelain README.md) ]]; then
            echo "No changes detected in README.md. Exiting."
            exit 0
          else
            echo "::set-output name=changed::true"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Updated time since birth"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/anupgautamm/BirthDateUpdate.git" HEAD:$(git rev-parse --abbrev-ref HEAD)
